### ISSUE TITLE
caching static files on client

### ISSUE THREAD

**Issue by benabraham** [pyvec/cz.pycon.org-2017#13]
Currently we have expiry for static files for 1 minute. 
We should set that to far future. 
That would mean adding cache busting system in place.

**Comment by starenka** [comment]
done

**Comment by benabraham** [comment]
Doesn't look like it on production.


```
Cache-Control:max-age=60
Date:Tue, 04 Apr 2017 10:06:56 GMT
Expires:Tue, 04 Apr 2017 10:07:56 GMT
```

**Comment by benabraham** [comment]
Cache busting is in place 👍 but let's set those expiry headers a bit further than a minute. If you have a minute :)

**Comment by starenka** [comment]
DOH! `1m` is not one month, but one minute...
