### ISSUE TITLE
link to financial aid shows CfP page

### ISSUE THREAD

**Issue by starenka** [pyvec/cz.pycon.org-2017#17]
in event submenu the financial aid link points to https://cz.pycon.org/2017/proposals/financial-aid (it's the missing slash at the end)

also router seems to be weird (the "good" page seemed to be routed via `proposals` router):
```
    url(r'^proposals/financial-aid$',
        TemplateView.as_view(template_name='proposals/talks_about.html'),
        name='financial-aid'),
```

I think removing this route would solve the issue, but have no time to prove it right now

**Comment by benabraham** [comment]
Because it's there https://github.com/pyvec/cz.pycon.org-2017/blob/master/pyconcz_2017/urls.py#L24

But question is what is correct behavior. 
Should the link work and show _Financial Aid_, is it ready?

**Comment by benabraham** [comment]
@starenka It’s linked to a wrong template.

**Comment by starenka** [comment]
I think it should just be deleted from main urls and as it works with ending `/` (and thus being serverd from `proposals.urls`) check https://cz.pycon.org/2017/proposals/financial-aid/ vs https://cz.pycon.org/2017/proposals/financial-aid

**Comment by benabraham** [comment]
The reason might be, that all static pages are listed there, in one place. But that's ”just“ technical problem.

My unanswered question is, if _Financial Aid_ page should be out in the wild. From it's content it seems so, it should be opened from 1st of April. I just don't know.

**Comment by Luminaar** [comment]
It is supposed to be in the wild. I was going to fix the link by adding / but then all the excitement with new design started.

**Comment by benabraham** [comment]
@Luminaar in that case merge my PR https://github.com/pyvec/cz.pycon.org-2017/pull/18 and deploy. If @starenka want’s to refactor that later he still can.

**Comment by starenka** [comment]
fixed by https://github.com/pyvec/cz.pycon.org-2017/commit/27de2d466fc0302af6c59d057d0e014d386d2c09
