### ISSUE TITLE
speakers vs keynoters - better handling (also in proposals)

### ISSUE THREAD

**Issue by starenka** [pyvec/cz.pycon.org-2017#33]
#next

**Comment by encukou** [comment]
@starenka Myslím že nikdo jiný než ty tuhle poznámku nerozluští :)
Je stále relevantní?

**Comment by benabraham** [comment]
I get it. While still relevant in 2019, we can't forget this.

**Comment by encukou** [comment]
> While still relevant in 2019, we can't forget this.

*Can't* or *can*?
