### ISSUE TITLE
npm install needs to be done with python 2

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/cz.pycon.org-2017#72]
Some node dependencies require compilation via node-gyp, but node-gyp doesn't support python3. The site is in python3, that means it's 99% chance a person installing the site locally will have a virtualenv with python3 active and his node-gyp compilation will fail.

The installation tutorial should suggest passing system python (or any kind of python 2) to the npm explicitly:

```
npm install --python=/usr/bin/python
```

**Comment by benabraham** [comment]
Probably not a problem on Windows though.

**Comment by honzajavorek** [comment]
Depends if you have multiple Python versions in the system, which could theoretically happen if you're seasoned developer.

**Comment by honzajavorek** [comment]
actually... 🤔 I have no idea how node-gyp works on Windows and if it works at all 😄 you'd need a compiler...

**Comment by benabraham** [comment]
This doesn't seem to be a problem ATM (Ubuntu 18, Windows 10).
