### ISSUE TITLE
markdown is required, but isn't installed with dev requirements

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/cz.pycon.org-2017#73]
When following the installation tutorial, opening the site in browser for the first time crashes on missing `markdown` package. I had to `pip install markdown` and then it worked.

**Comment by starenka** [comment]
I don't like the requirements handling at all... I'd simplify it for casual requirements.txt and requirements_dev.txt

**Comment by starenka** [comment]
btw it is in "main" requirements...
