### ISSUE TITLE
Video embeds at talk detail

### ISSUE THREAD

**Issue by hroncok** [pyvec/cz.pycon.org-2017#90]
Last year, we froze the website and somebody requested to add links to videos there. We decided to don't do it (too much work), so I'm opening this ticket before this years website gets frozen.

The videos links should go to:

 * [Schedule](https://cz.pycon.org/2017/speakers/schedule/)
 * [Talks](https://cz.pycon.org/2017/speakers/talks/)
 * Talk detail such as [this one](https://cz.pycon.org/2017/speakers/detail/talk/1/)
 * It should be visible from the [front page](https://cz.pycon.org/2017/)
   * maybe change the *Talks* link to say *Talks + Videos*

**Comment by benabraham** [comment]
Agree, but not sure if Schedule should be kept at all.

**Comment by hroncok** [comment]
Well somebody might find it useful, so why remove it.

**Comment by benabraham** [comment]
Also I'd prefer this to be direct embeds in talks details.

**Comment by benabraham** [comment]
Just embeds seem enough. 

I see no reason to link them in listings (Schedule or Talks).

There could be some kind of promotion on the homepage, but the majority will be from social media / search engines directly to talks' details anyway.

**Comment by hroncok** [comment]
Agreed.
